
source "null" "autogenerated_1" {
  communicator   = "winrm"
  winrm_host     = "${var.winrm_password}"
  winrm_insecure = true
  winrm_password = "${var.winrm_password}"
  winrm_port     = 5986
  winrm_timeout  = "30s"
  winrm_use_ntlm = true
  winrm_use_ssl  = true
  winrm_username = "${var.winrm_username}"
}

build {
  sources = ["source.null.autogenerated_1"]

  provisioner "file" {
    destination = "C:\\DryDeploy\\"
    source      = ".\functions\Initialize-DryPkgMgmtComponent.ps1"
  }

  dynamic "windows_feature" {
    for_each = var.windows_feature
    provisioner "powershell" {
      elevated_password = "${var.winrm_password}"
      elevated_user     = "${var.winrm_username}"
      inline            = [
        "Install-WindowsFeature -Name ${windows_feature.value[\"Name\"]}"]
      valid_exit_codes  = [0]
    }
  }
}