
source "vsphere-iso" "autogenerated_1" {
  CPUs                 = 4
  NestedHV             = true
  RAM                  = 4096
  RAM_reserve_all      = true
  boot_command         = ["<enter>"]
  boot_wait            = "2s"
  cd_files             = ["./*"]
  cluster              = "${var.vcenter_cluster}"
  communicator         = "winrm"
  convert_to_template  = true
  cpu_cores            = 4
  datastore            = "${var.vcenter_datastore}"
  disk_controller_type = "lsilogic-sas"
  firmware             = "efi"
  folder               = "${var.vcenter_folder}"
  guest_os_type        = "windows9Server64Guest"
  insecure_connection  = "${var.insecure_connection}"
  iso_paths            = ["${var.vcenter_iso_ws2022_desktop}", "${var.vcenter_iso_vmwaretools}"]
  network_adapters {
    network      = "${var.vcenter_network}"
    network_card = "vmxnet3"
  }
  password     = "${var.vcenter_password}"
  remove_cdrom = true
  storage {
    disk_controller_index = 0
    disk_size             = 102400
    disk_thin_provisioned = true
  }
  username       = "${var.vcenter_username}"
  vcenter_server = "${var.vcenter_server}"
  vm_name        = "ws22-std-gui-ltsc"
  vm_version     = 19
  winrm_password = "${var.winrm_password}"
  winrm_username = "${var.winrm_username}"
}

build {
  sources = ["source.vsphere-iso.autogenerated_1"]

  provisioner "powershell" {
    elevated_password = "${var.winrm_password}"
    elevated_user     = "${var.winrm_username}"
    inline            = ["[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12", "Set-PackageSource -Name PSGallery -Trusted", "Install-PackageProvider -Name Nuget -MinimumVersion 2.8.5.201 -Scope AllUsers -Confirm:$false -Force"]
    max_retries       = "3"
    pause_before      = "2m0s"
  }

  provisioner "windows-restart" {
    restart_check_command = "powershell -command \"& {Write-Output 'restarted.'}\""
  }

  provisioner "powershell" {
    elevated_password = "${var.winrm_password}"
    elevated_user     = "${var.winrm_username}"
    inline            = ["[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12", "Install-Module -Name PackageManagement -MinimumVersion 1.4.6 -Scope AllUsers -AllowClobber -Repository PSGallery -Confirm:$false -Force"]
    max_retries       = "3"
    pause_before      = "2s"
  }

  provisioner "windows-restart" {
    restart_check_command = "powershell -command \"& {Write-Output 'restarted.'}\""
  }

  provisioner "powershell" {
    elevated_password = "${var.winrm_password}"
    elevated_user     = "${var.winrm_username}"
    inline            = ["[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12", "Install-Module -Name PowerShellGet -MinimumVersion 2.2.5 -Scope AllUsers -AllowClobber -Repository PSGallery -Confirm:$false -Force -WarningAction Continue", "Remove-Module -Name PowerShellGet -ErrorAction Ignore", "Remove-Module -Name PackageManagement -ErrorAction Ignore", "$ModulesToDelete = @(Get-Module -Name PowerShellGet -ListAvailable | Where-Object Version -lt 2.2.5)", "foreach ($m in $ModulesToDelete) { Remove-Item -Path (Split-Path -Path $m.Path) -Recurse -Force }"]
    max_retries       = "3"
    pause_before      = "2s"
  }

  provisioner "windows-restart" {
    restart_check_command = "powershell -command \"& {Write-Output 'restarted.'}\""
  }

  provisioner "powershell" {
    elevated_password = "${var.winrm_password}"
    elevated_user     = "${var.winrm_username}"
    inline            = ["f:\\Scripts\\ConfigPreReboot.ps1 -Configfile f:\\ws22-std-gui-ltsc-OSConfig.json"]
    max_retries       = "3"
    pause_before      = "2s"
  }

  provisioner "windows-restart" {
    restart_check_command = "powershell -command \"& {Write-Output 'restarted.'}\""
  }

  provisioner "powershell" {
    elevated_password = "${var.winrm_password}"
    elevated_user     = "${var.winrm_username}"
    inline            = ["f:\\Scripts\\ConfigPostReboot.ps1 -Configfile f:\\ws22-std-gui-ltsc-OSConfig.json"]
    max_retries       = "3"
  }

  provisioner "windows-restart" {
    restart_check_command = "powershell -command \"& {Write-Output 'restarted.'}\""
  }

  provisioner "powershell" {
    elevated_password = "${var.winrm_password}"
    elevated_user     = "${var.winrm_username}"
    inline            = ["f:\\Scripts\\ConfigUpdates.ps1 -Configfile f:\\ws22-std-gui-ltsc-OSConfig.json"]
    max_retries       = "2"
    timeout           = "2h0m0s"
  }

  provisioner "windows-restart" {
    max_retries           = "5"
    pause_before          = "30s"
    restart_check_command = "powershell -command \"& {Write-Output 'restarted.'}\""
    restart_timeout       = "30m"
  }

  provisioner "powershell" {
    elevated_password = "${var.winrm_password}"
    elevated_user     = "${var.winrm_username}"
    inline            = ["f:\\Scripts\\ConfigUpdates.ps1 -Configfile f:\\ws22-std-gui-ltsc-OSConfig.json"]
    max_retries       = "2"
  }

  provisioner "windows-restart" {
    max_retries           = "5"
    restart_check_command = "powershell -command \"& {Write-Output 'restarted.'}\""
    restart_timeout       = "30m"
  }

  provisioner "powershell" {
    elevated_password = "${var.winrm_password}"
    elevated_user     = "${var.winrm_username}"
    inline            = ["f:\\Scripts\\ConfigUpdates.ps1 -Configfile f:\\ws22-std-gui-ltsc-OSConfig.json"]
    max_retries       = "2"
  }

  provisioner "windows-restart" {
    max_retries           = "5"
    restart_check_command = "powershell -command \"& {Write-Output 'restarted.'}\""
    restart_timeout       = "30m"
  }

  provisioner "powershell" {
    elevated_password = "${var.winrm_password}"
    elevated_user     = "${var.winrm_username}"
    inline            = ["Try { Copy-Item -Path F:\\Scripts\\ConfigureWinRM-https.ps1 -Destination C:\\Temp\\ -Force } Catch { Throw $_ }"]
    max_retries       = "2"
  }

  provisioner "powershell" {
    elevated_password = "${var.winrm_password}"
    elevated_user     = "${var.winrm_username}"
    inline            = ["f:\\Scripts\\ConfigLast.ps1 -Configfile f:\\ws22-std-gui-ltsc-OSConfig.json"]
    max_retries       = "2"
  }

}
